version: '3'

services:

  mysql-development:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: pass1314
      MYSQL_DATABASE: chat
    ports:
      - "3308:3306"
  admin:    
    image: adminer    
    ports:      
      - "8080:8080"